"""inheritance user-seller-buyer

Revision ID: 03d395be6627
Revises: e16e6b8c5aca
Create Date: 2024-03-31 00:00:17.004741

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "03d395be6627"
down_revision: Union[str, None] = "e16e6b8c5aca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "User",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("surname", sa.String(length=50), nullable=False),
        sa.Column("password", sa.String(length=25), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_User_id"), "User", ["id"], unique=False)
    op.drop_constraint("Buyer_email_key", "Buyer", type_="unique")
    op.create_foreign_key(
        "fk_buyer_user_id", "Buyer", "User", ["id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("Buyer", "name")
    op.drop_column("Buyer", "email")
    op.drop_column("Buyer", "surname")
    op.drop_column("Buyer", "password")
    op.drop_constraint("Seller_email_key", "Seller", type_="unique")
    op.create_foreign_key(
        "fk_seller_user_id", "Seller", "User", ["id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("Seller", "name")
    op.drop_column("Seller", "email")
    op.drop_column("Seller", "surname")
    op.drop_column("Seller", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Seller",
        sa.Column(
            "password", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "Seller",
        sa.Column(
            "surname", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "Seller",
        sa.Column("email", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    op.add_column(
        "Seller",
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    op.drop_constraint("fk_seller_user_id", "Seller", type_="foreignkey")
    op.create_unique_constraint("Seller_email_key", "Seller", ["email"])
    op.add_column(
        "Buyer",
        sa.Column(
            "password", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "Buyer",
        sa.Column(
            "surname", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "Buyer",
        sa.Column("email", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    op.add_column(
        "Buyer",
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    op.drop_constraint("fk_buyer_user_id", "Buyer", type_="foreignkey")
    op.create_unique_constraint("Buyer_email_key", "Buyer", ["email"])
    op.drop_index(op.f("ix_User_id"), table_name="User")
    op.drop_table("User")
    # ### end Alembic commands ###
