"""review table

Revision ID: 14648af86b79
Revises: 2816457297cc
Create Date: 2024-05-18 14:33:42.175400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14648af86b79'
down_revision: Union[str, None] = '2816457297cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_seller_product', sa.Integer(), nullable=False),
    sa.Column('id_buyer', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_buyer'], ['Buyer.id'], name='fk_review_buyer_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_seller_product'], ['SellerProduct.id'], name='fk_review_seller_product_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Review_id_buyer'), 'Review', ['id_buyer'], unique=False)
    op.create_index(op.f('ix_Review_id_seller_product'), 'Review', ['id_seller_product'], unique=False)
    op.add_column('SellerProduct', sa.Column('stars', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SellerProduct', 'stars')
    op.drop_index(op.f('ix_Review_id_seller_product'), table_name='Review')
    op.drop_index(op.f('ix_Review_id_buyer'), table_name='Review')
    op.drop_table('Review')
    # ### end Alembic commands ###
