"""product_line column id_size added

Revision ID: 14686a9cb25f
Revises: b10ffcd10772
Create Date: 2024-05-27 18:48:39.264697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14686a9cb25f'
down_revision: Union[str, None] = 'b10ffcd10772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ProductLine', sa.Column('id_size', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_product_line_size_id', 'ProductLine', 'Size', ['id_size'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_product_line_size_id', 'ProductLine', type_='foreignkey')
    op.drop_column('ProductLine', 'id_size')
    # ### end Alembic commands ###
