"""add state column for orders

Revision ID: 2f4220a451e1
Revises: 8acad48495a4
Create Date: 2024-05-18 00:05:28.939608

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "2f4220a451e1"
down_revision: Union[str, None] = "8acad48495a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Define the enum type for orders state
orderstate_enum = postgresql.ENUM(
    "PENDING",
    "CONFIRMED",
    "CANCELLED",
    "SHIPPED",
    "DELIVERED",
    name="orderstate",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create the enum type in the database
    orderstate_enum.create(op.get_bind())

    op.add_column(
        "Order",
        sa.Column(
            "state",
            sa.Enum(
                "PENDING",
                "CONFIRMED",
                "CANCELLED",
                "SHIPPED",
                "DELIVERED",
                name="orderstate",
            ),
            nullable=False,
            server_default="PENDING",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Order", "state")

    # Drop the enum type from the database
    orderstate_enum.drop(op.get_bind())

    # ### end Alembic commands ###
