"""accept null as order_date

Revision ID: 32e8c06989a8
Revises: 2816457297cc
Create Date: 2024-05-15 11:53:20.768501

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "32e8c06989a8"
down_revision: Union[str, None] = "2816457297cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Order", "order_date", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Order", "order_date", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###
