"""remove size from product 2

Revision ID: 641104f6facb
Revises: 56301e938afa
Create Date: 2024-04-29 10:57:14.107344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '641104f6facb'
down_revision: Union[str, None] = '56301e938afa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Clothes', 'size')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Clothes', sa.Column('size', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
