"""create Size table

Revision ID: 8884c2b82e21
Revises: eff7bba2d693
Create Date: 2024-04-30 13:16:46.883561

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8884c2b82e21"
down_revision: Union[str, None] = "eff7bba2d693"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Size",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("size", sa.String(length=255), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("seller_product_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["seller_product_id"],
            ["SellerProduct.id"],
            name="fk_size_seller_product_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("Clothes", "size")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Clothes",
        sa.Column("size", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    op.drop_table("Size")
    # ### end Alembic commands ###
