"""review table

Revision ID: 96eb1c6adef8
Revises: 14648af86b79
Create Date: 2024-05-18 14:55:58.129296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96eb1c6adef8'
down_revision: Union[str, None] = '14648af86b79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('SellerProduct', 'stars',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=1, scale=1),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('SellerProduct', 'stars',
               existing_type=sa.Numeric(precision=1, scale=1),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
