"""product_line column estimated date added

Revision ID: b10ffcd10772
Revises: 918d1478aa31
Create Date: 2024-05-27 17:36:15.388970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b10ffcd10772'
down_revision: Union[str, None] = '918d1478aa31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ProductLine', sa.Column('estimated_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ProductLine', 'estimated_date')
    # ### end Alembic commands ###
