"""order type added to table

Revision ID: bdf4976ceaf5
Revises: ee47d9c3e2a6
Create Date: 2024-06-02 22:33:02.791337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'bdf4976ceaf5'
down_revision: Union[str, None] = 'ee47d9c3e2a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Define the enum type for orders type
ordertype_enum = postgresql.ENUM(
    "STANDARD",
    "PREMIUM",
    name="ordertype",
)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    ordertype_enum.create(op.get_bind())
    op.add_column('Order', sa.Column('type', sa.Enum('STANDARD', 'PREMIUM', name='ordertype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Order', 'type')
    ordertype_enum.drop(op.get_bind())
    # ### end Alembic commands ###
