"""add estimated_date column to order

Revision ID: c5ac938b6e3a
Revises: dcdcf7e91f9f
Create Date: 2024-05-27 11:13:21.787944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5ac938b6e3a'
down_revision: Union[str, None] = 'dcdcf7e91f9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Order', sa.Column('estimated_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Order', 'estimated_date')
    # ### end Alembic commands ###
