"""changing decimals in stars

Revision ID: d2c856df9e8e
Revises: 96eb1c6adef8
Create Date: 2024-05-18 15:15:32.987978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2c856df9e8e'
down_revision: Union[str, None] = '96eb1c6adef8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('SellerProduct', 'stars',
               existing_type=sa.NUMERIC(precision=1, scale=1),
               type_=sa.Numeric(precision=2, scale=1),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('SellerProduct', 'stars',
               existing_type=sa.Numeric(precision=2, scale=1),
               type_=sa.NUMERIC(precision=1, scale=1),
               existing_nullable=True)
    # ### end Alembic commands ###
