"""change composite primary key to single primary key in shopping cart table

Revision ID: d64e07512f44
Revises: 215bae6bf3be
Create Date: 2024-05-04 18:10:06.089341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd64e07512f44'
down_revision: Union[str, None] = '215bae6bf3be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('InShoppingCart', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('InShoppingCart', 'id')
    # ### end Alembic commands ###
