"""db improvements

Revision ID: d753c9f00baa
Revises: 3a6bc11fb4ea
Create Date: 2024-03-21 14:06:30.114959

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d753c9f00baa"
down_revision: Union[str, None] = "3a6bc11fb4ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("BuyerOwnsCard")
    op.create_index(op.f("ix_Address_id"), "Address", ["id"], unique=False)
    op.create_index(op.f("ix_Buyer_id"), "Buyer", ["id"], unique=False)
    op.create_index(op.f("ix_Card_id"), "Card", ["id"], unique=False)
    op.create_index(op.f("ix_Category_id"), "Category", ["id"], unique=False)
    op.create_index(op.f("ix_Image_id"), "Image", ["id"], unique=False)
    op.create_index(
        op.f("ix_InShoppingCart_id_buyer"), "InShoppingCart", ["id_buyer"], unique=False
    )
    op.create_index(
        op.f("ix_InShoppingCart_id_seller_product"),
        "InShoppingCart",
        ["id_seller_product"],
        unique=False,
    )
    op.create_index(
        op.f("ix_InWishList_id_buyer"), "InWishList", ["id_buyer"], unique=False
    )
    op.create_index(
        op.f("ix_InWishList_id_seller_product"),
        "InWishList",
        ["id_seller_product"],
        unique=False,
    )
    op.create_index(op.f("ix_Order_id"), "Order", ["id"], unique=False)
    op.create_index(op.f("ix_Product_id"), "Product", ["id"], unique=False)
    op.create_index(op.f("ix_ProductLine_id"), "ProductLine", ["id"], unique=False)
    op.create_index(op.f("ix_RefundProduct_id"), "RefundProduct", ["id"], unique=False)
    op.create_index(op.f("ix_Seller_id"), "Seller", ["id"], unique=False)
    op.create_index(op.f("ix_SellerProduct_id"), "SellerProduct", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_SellerProduct_id"), table_name="SellerProduct")
    op.drop_index(op.f("ix_Seller_id"), table_name="Seller")
    op.drop_index(op.f("ix_RefundProduct_id"), table_name="RefundProduct")
    op.drop_index(op.f("ix_ProductLine_id"), table_name="ProductLine")
    op.drop_index(op.f("ix_Product_id"), table_name="Product")
    op.drop_index(op.f("ix_Order_id"), table_name="Order")
    op.drop_index(op.f("ix_InWishList_id_seller_product"), table_name="InWishList")
    op.drop_index(op.f("ix_InWishList_id_buyer"), table_name="InWishList")
    op.drop_index(
        op.f("ix_InShoppingCart_id_seller_product"), table_name="InShoppingCart"
    )
    op.drop_index(op.f("ix_InShoppingCart_id_buyer"), table_name="InShoppingCart")
    op.drop_index(op.f("ix_Image_id"), table_name="Image")
    op.drop_index(op.f("ix_Category_id"), table_name="Category")
    op.drop_index(op.f("ix_Card_id"), table_name="Card")
    op.drop_index(op.f("ix_Buyer_id"), table_name="Buyer")
    op.drop_index(op.f("ix_Address_id"), table_name="Address")
    op.create_table(
        "BuyerOwnsCard",
        sa.Column("id_card", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id_buyer", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["id_buyer"], ["Buyer.id"], name="BuyerOwnsCard_id_buyer_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["id_card"], ["Card.id"], name="BuyerOwnsCard_id_card_fkey"
        ),
        sa.PrimaryKeyConstraint("id_card", "id_buyer", name="BuyerOwnsCard_pkey"),
    )
    # ### end Alembic commands ###
