"""naming and updating constraints

Revision ID: e16e6b8c5aca
Revises: 11af73214744
Create Date: 2024-03-30 11:59:07.469641

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "e16e6b8c5aca"
down_revision: Union[str, None] = "11af73214744"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("Address_id_buyer_fkey", "Address", type_="foreignkey")
    op.create_foreign_key(
        "fk_address_buyer_id",
        "Address",
        "Buyer",
        ["id_buyer"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("Card_id_buyer_fkey", "Card", type_="foreignkey")
    op.create_foreign_key(
        "fk_card_buyer_id", "Card", "Buyer", ["id_buyer"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        "InShoppingCart_id_seller_product_fkey", "InShoppingCart", type_="foreignkey"
    )
    op.drop_constraint(
        "InShoppingCart_id_buyer_fkey", "InShoppingCart", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_cart_seller_product_id",
        "InShoppingCart",
        "SellerProduct",
        ["id_seller_product"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_cart_buyer_id",
        "InShoppingCart",
        "Buyer",
        ["id_buyer"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("InWishList_id_buyer_fkey", "InWishList", type_="foreignkey")
    op.drop_constraint(
        "InWishList_id_seller_product_fkey", "InWishList", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_wish_list_seller_product_id",
        "InWishList",
        "SellerProduct",
        ["id_seller_product"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_wish_list_buyer_id",
        "InWishList",
        "Buyer",
        ["id_buyer"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("Order_id_buyer_fkey", "Order", type_="foreignkey")
    op.create_foreign_key(
        "fk_order_buyer_id", "Order", "Buyer", ["id_buyer"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("Product_id_category_fkey", "Product", type_="foreignkey")
    op.create_foreign_key(
        "fk_product_category_id",
        "Product",
        "Category",
        ["id_category"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("ProductLine_id_order_fkey", "ProductLine", type_="foreignkey")
    op.create_foreign_key(
        "fk_product_line_order_id",
        "ProductLine",
        "Order",
        ["id_order"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "RefundProduct_id_product_line_fkey", "RefundProduct", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_refund_product_product_line_id",
        "RefundProduct",
        "ProductLine",
        ["id_product_line"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "SellerProduct_id_seller_fkey", "SellerProduct", type_="foreignkey"
    )
    op.drop_constraint(
        "SellerProduct_id_product_fkey", "SellerProduct", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_seller_product_seller_id",
        "SellerProduct",
        "Seller",
        ["id_seller"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_seller_product_product_id",
        "SellerProduct",
        "Product",
        ["id_product"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_seller_product_product_id", "SellerProduct", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_seller_product_seller_id", "SellerProduct", type_="foreignkey"
    )
    op.create_foreign_key(
        "SellerProduct_id_product_fkey",
        "SellerProduct",
        "Product",
        ["id_product"],
        ["id"],
    )
    op.create_foreign_key(
        "SellerProduct_id_seller_fkey", "SellerProduct", "Seller", ["id_seller"], ["id"]
    )
    op.drop_constraint(
        "fk_refund_product_product_line_id", "RefundProduct", type_="foreignkey"
    )
    op.create_foreign_key(
        "RefundProduct_id_product_line_fkey",
        "RefundProduct",
        "ProductLine",
        ["id_product_line"],
        ["id"],
    )
    op.drop_constraint("fk_product_line_order_id", "ProductLine", type_="foreignkey")
    op.create_foreign_key(
        "ProductLine_id_order_fkey", "ProductLine", "Order", ["id_order"], ["id"]
    )
    op.drop_constraint("fk_product_category_id", "Product", type_="foreignkey")
    op.create_foreign_key(
        "Product_id_category_fkey", "Product", "Category", ["id_category"], ["id"]
    )
    op.drop_constraint("fk_order_buyer_id", "Order", type_="foreignkey")
    op.create_foreign_key("Order_id_buyer_fkey", "Order", "Buyer", ["id_buyer"], ["id"])
    op.drop_constraint("fk_wish_list_buyer_id", "InWishList", type_="foreignkey")
    op.drop_constraint(
        "fk_wish_list_seller_product_id", "InWishList", type_="foreignkey"
    )
    op.create_foreign_key(
        "InWishList_id_seller_product_fkey",
        "InWishList",
        "SellerProduct",
        ["id_seller_product"],
        ["id"],
    )
    op.create_foreign_key(
        "InWishList_id_buyer_fkey", "InWishList", "Buyer", ["id_buyer"], ["id"]
    )
    op.drop_constraint("fk_cart_buyer_id", "InShoppingCart", type_="foreignkey")
    op.drop_constraint(
        "fk_cart_seller_product_id", "InShoppingCart", type_="foreignkey"
    )
    op.create_foreign_key(
        "InShoppingCart_id_buyer_fkey", "InShoppingCart", "Buyer", ["id_buyer"], ["id"]
    )
    op.create_foreign_key(
        "InShoppingCart_id_seller_product_fkey",
        "InShoppingCart",
        "SellerProduct",
        ["id_seller_product"],
        ["id"],
    )
    op.drop_constraint("fk_card_buyer_id", "Card", type_="foreignkey")
    op.create_foreign_key("Card_id_buyer_fkey", "Card", "Buyer", ["id_buyer"], ["id"])
    op.drop_constraint("fk_address_buyer_id", "Address", type_="foreignkey")
    op.create_foreign_key(
        "Address_id_buyer_fkey", "Address", "Buyer", ["id_buyer"], ["id"]
    )
    # ### end Alembic commands ###
