"""new table sizes 2

Revision ID: e27d94632660
Revises: 5261b6aeccec
Create Date: 2024-04-29 16:15:35.893556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e27d94632660'
down_revision: Union[str, None] = '5261b6aeccec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Size',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('seller_product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['seller_product_id'], ['SellerProduct.id'], name='fk_size_seller_product_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Size')
    # ### end Alembic commands ###
