"""age_restricted column for products

Revision ID: ec5e7bfeb588
Revises: 1139542f4f34
Create Date: 2024-04-26 14:55:27.388172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec5e7bfeb588'
down_revision: Union[str, None] = '1139542f4f34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SellerProduct', sa.Column('age_restricted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SellerProduct', 'age_restricted')
    # ### end Alembic commands ###
