<<<<<<<< HEAD:Back/app/alembic/versions/ee47d9c3e2a6_order_state_default_changed_to_.py
"""order state default changed to confirmesd

Revision ID: ee47d9c3e2a6
Revises: 14686a9cb25f
Create Date: 2024-05-29 18:43:25.994099
========
"""accept null as order_date

Revision ID: 32e8c06989a8
Revises: 2816457297cc
Create Date: 2024-05-15 11:53:20.768501
>>>>>>>> 5052ee7 (refactor: improve sales system (#33)):Back/app/alembic/versions/32e8c06989a8_accept_null_as_order_date.py

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
<<<<<<<< HEAD:Back/app/alembic/versions/ee47d9c3e2a6_order_state_default_changed_to_.py
revision: str = 'ee47d9c3e2a6'
down_revision: Union[str, None] = '14686a9cb25f'
========
revision: str = "32e8c06989a8"
down_revision: Union[str, None] = "2816457297cc"
>>>>>>>> 5052ee7 (refactor: improve sales system (#33)):Back/app/alembic/versions/32e8c06989a8_accept_null_as_order_date.py
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
<<<<<<<< HEAD:Back/app/alembic/versions/ee47d9c3e2a6_order_state_default_changed_to_.py
    pass
========
    op.alter_column(
        "Order", "order_date", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
>>>>>>>> 5052ee7 (refactor: improve sales system (#33)):Back/app/alembic/versions/32e8c06989a8_accept_null_as_order_date.py
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
<<<<<<<< HEAD:Back/app/alembic/versions/ee47d9c3e2a6_order_state_default_changed_to_.py
    pass
========
    op.alter_column(
        "Order", "order_date", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
>>>>>>>> 5052ee7 (refactor: improve sales system (#33)):Back/app/alembic/versions/32e8c06989a8_accept_null_as_order_date.py
    # ### end Alembic commands ###
