"""date of birth for buyers and sellers

Revision ID: eff7bba2d693
Revises: ec5e7bfeb588
Create Date: 2024-04-28 16:04:23.870023

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eff7bba2d693"
down_revision: Union[str, None] = "ec5e7bfeb588"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Buyer", sa.Column("birth_date", sa.Date(), nullable=False))
    op.add_column("Seller", sa.Column("birth_date", sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Seller", "birth_date")
    op.drop_column("Buyer", "birth_date")
    # ### end Alembic commands ###
